# Visualizing a Decision Tree

http://scikit-learn.org/stable/datasets/

## Checkout sample Datasets

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
print iris.feature_names  # metadata: names of the features
print iris.target_names  # metadata: names of the different types of flowers

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [4]:
# print iris.data  # features and examples themselves
print iris.data[0]  # first flower
print iris.target[0]  # contains the labels

[ 5.1  3.5  1.4  0.2]
0


In [5]:
# print entire dataset
# for i in xrange(len(iris.target)):
#     print "Example %d: label %s, features %s" % (i, iris.target[i], iris.data[i])

# Testing Data
# Examples used to test the classifier's accuracy
# Not part of the training data

In [6]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

In [7]:
iris = load_iris()
# here, we remove the first example of each flower
# found at indices: 0, 50, 100
test_idx = [0, 50, 100]

In [8]:
# create 2 new sets of variables, for training and testing
# training data
# remove the entires from the data and target variables
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

In [9]:
# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [10]:
# create new classifier
clf = tree.DecisionTreeClassifier()
# train on training data
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [11]:
# what we expect
print test_target

[0 1 2]


In [12]:
# what tree predicts
print clf.predict(test_data)

[0 1 2]


In [13]:
# Visualize
# from scikit decision tree tutorial: http://scikit-learn.org/stable/modules/tree.html
from sklearn.externals.six import StringIO
import pydotplus

In [ ]:
dot_data = StringIO()
tree.export_graphviz(clf, out_file=dot_data,
                     feature_names=iris.feature_names,
                     class_names=iris.target_names,
                     filled=True, rounded=True,
                     impurity=False)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")